import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/navigation/Header";


export const metadata: Metadata = {
  title: "cyber Safe",
  description: "Generated by Hana Elhady",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
  <body className= "min-h-screen">
  <Header />
  <div className="container flex flex-col ">
      {children}
      
    </div>
  </body>
</html>

  );
}
